fix yml

diff --git a/.github/workflows/ping.yml b/.github/workflows/ping.yml
--- a/.github/workflows/ping.yml
+++ b/.github/workflows/ping.yml
@@ -5,31 +5,32 @@ on:
     branches:
       - '*'
 
+jobs:
 
-ping:
-  runs-on: ubuntu-18.04
-  steps:
-    - name: curl actuator
-      id: ping
-      run: |
-        echo "::set-output name=status::$(curl ${{secrets.SERVER_HOST}}/api/actuator/health)"
+  ping:
+    runs-on: ubuntu-18.04
+    steps:
+      - name: curl actuator
+        id: ping
+        run: |
+          echo "::set-output name=status::$(curl ${{secrets.SERVER_HOST}}/api/actuator/health)"
 
-    - name: health check
-      run: |
-        if [[ ${{ steps.ping.outputs.status }} != *"U0P"* ]]; then
-          echo "health check is failed"
-          exit 1
-        fi
-        echo "It's OK"
+      - name: health check
+        run: |
+          if [[ ${{ steps.ping.outputs.status }} != *"U0P"* ]]; then
+            echo "health check is failed"
+            exit 1
+          fi
+          echo "It's OK"
 
-    - name: telega
-      if: ${{ failure() }}
-      uses: appleboy/telegram-action@master
-      with:
-        to: ${{ secrets.TELEGRAM_TO }}
-        token: ${{ secrets.TELEGRAM_TOKEN }}
-        message: |
-          Health check of the:
-          ${{secrets.SERVER_HOST}}/api/actuator/health
-          failed with the result:
-          ${{ steps.ping.outputs.status }}
+      - name: telega
+        if: ${{ failure() }}
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_TO }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          message: |
+            Health check of the:
+            ${{secrets.SERVER_HOST}}/api/actuator/health
+            failed with the result:
+            ${{ steps.ping.outputs.status }}
